lesson_3
paveltas/It_academy pull request #5
Opened 2023-05-25 08:52 UTC by paveltas

2023-05-29 13:32 UTC, a-kosak-mbx requested changes

2023-05-29 13:32 UTC, a-kosak-mbx commented on Lesson_3/Lesson_3.py
> +    return ''.join([el for i, el in enumerate(new_str) if el not in new_str[:i]])
Плохо. Очень высокая сложность. Каждый раз делается срез и поиск на каждой итерации занимает O(N), то есть общая сложность алгоритма O(N^2). Нужно хотя бы N*log2(N).

2023-05-29 13:32 UTC, a-kosak-mbx commented on Lesson_3/Lesson_3.py
> +    lower = sum([1 for el in value if el in 'abcdefghijklmnopqrstuvwxyz'])
Плохо. Как минимум есть соответствующие методы для проверки. Как максимум лучше проверять диапазон, а не вхождение в строку, поиск по которой осуществляется за O(N).

2023-05-31 15:06 UTC, a-kosak-mbx requested changes

2023-05-31 15:06 UTC, a-kosak-mbx commented on Lesson_3/Lesson_3.py
> +    return ''.join(k for k in dct_)
Идея с диктом отличная, но было бы лучше использовать методы replace, fromkeys и join(dct_).
То есть что-то вроде `return ''.join(dict.fromkeys(value.replace(' ', '')))`

2023-05-31 15:06 UTC, a-kosak-mbx commented on Lesson_3/Lesson_3.py
> +    lower = sum(1 for el in value if ord(el) in range(97, 123))
Опять та же ошибка. Ничего принципиально не поменялось же. Толку от того, что вы не строки используете, а их байтовые представления? Длина осталась та же и сложность поиска тоже линейная.

2023-05-31 16:02 UTC, paveltas commented on Lesson_3/Lesson_3.py
> +    lower = sum(1 for el in value if ord(el) in range(97, 123))
Прошу прощения, делал на работе в спешке и скопировал не тот вариант из черновика.
здесь должно быть if A <= el <=Z. то же самое для lower. я решил не использовать isupper так как еще нужна проверка на то что записаны именно латинские буквы. а это, как я понимаю через аски все тем же перебором.

2023-06-18 15:46 UTC, a-kosak-mbx approved these changes

2023-06-19 11:53 UTC, merged