add lesson_5
paveltas/It_academy pull request #9
Opened 2023-07-24 05:51 UTC by paveltas

2023-07-26 15:02 UTC, a-kosak-mbx requested changes
Нужны исправления.

2023-07-26 15:02 UTC, a-kosak-mbx commented on lesson_5/lesson_5.py
> +print('unique_numbers ->', unique_numbers([8, 1, 2, 3, 1, 1, 2, 10, 2, 3, 3, 4, 5, 6]))
Здесь выводятся все лементы, просто в единственном варианте.

2023-07-26 15:02 UTC, a-kosak-mbx commented on lesson_5/lesson_5.py
> +tuple_ = ('a', 'b', 'c')
Скобки лишние.

2023-07-26 15:02 UTC, a-kosak-mbx commented on lesson_5/lesson_5.py
> +tuple_ = ((1, 2, 3),)
Внешние скобки лишние.

2023-07-26 15:02 UTC, a-kosak-mbx commented on lesson_5/lesson_5.py
> +print('\n'.join(new_cities_set), end='\n\n')
Что-то вообще решение не соответствуте заданию.
Вот вообще не понимаю, что в этих строчках происходит. Общий смысл от меня ускользает.

2023-07-26 15:02 UTC, a-kosak-mbx commented on lesson_5/lesson_5.py
> +    return len(set(value.split()))
Как минимум не учтено, что слова, записанные в разных регистрах - это одни и те же слова.

2023-07-26 15:02 UTC, a-kosak-mbx commented on lesson_5/lesson_5.py
> +    dct[n] = set_
Лучше добавлять какое-то слово вроде counter, number, quantity и т. д., если в переменной хранится счетчик.

2023-07-26 15:02 UTC, a-kosak-mbx commented on lesson_5/lesson_5.py
> +print('lst, new_lst ->', lst, new_lst)
а можно в одну строчку?

2023-07-27 07:24 UTC, paveltas commented on lesson_5/lesson_5.py
> +print('\n'.join(new_cities_set), end='\n\n')
в задании сказано 

# Входные данные
# Программа получает на вход количество стран N. Далее идет N строк, каждая строка начинается с названия страны,
# затем идут названия городов этой страны. В следующей строке записано число M,
# далее идут M запросов — названия каких-то M городов, перечисленных выше.

здесь я получаю количество стран - first_number = int(input('Enter first number '))

здесь я составляю словарь используя first_number как ограничение. Для того что бы взять только те элементы словаря что входят в заданные рамки я использую enumerate(countries.items()) и сравниваю if i < first_number - new_countries_dct = {k: v for i, (k, v) in enumerate(countries.items()) if i < first_number}

здесь я вывожу в ряд, сначала название странны, а за ним города к ней относящиеся. и так для каждой страны - print('\n'.join(f'{key} {" ".join(value)}' for key, value in new_countries_dct.items()), end='\n\n')

здесь я получаю  число городов, которые нужно взять из списка cities, я его создавал в начале задачи.  -second_number = int(input('Enter second number '))

здесь я на основе second_number составляю множество из  cities, через срез - new_cities_set = set(cities[:second_number])

здесь вывожу названия городов в ряд - print('\n'.join(new_cities_set), end='\n\n')
эти города будут запросами для поиска в каких странах они есть

Если это не, то что нужно тогда объясните что нужно сделать, пожалуйста. Потому что я могу еще предположить что от нас хотели, что бы после ввода числа городов, мы вручную их вбивали. На основании городов выведенных до этого, когда мы выводили странны и их города. Но тогда я не понимаю зачем мы создавали отдельный список городов, как было сказано в условии (# Дан список стран и городов каждой страны. Затем даны названия городов.), если мы его ни где не используем.

2023-08-21 08:09 UTC, a-kosak-mbx requested changes
Все хорошо, кроме годородов/стран. Описал, как правильно сделать.

2023-08-21 08:09 UTC, a-kosak-mbx commented on lesson_5/lesson_5.py
> +        print(f'Города {city} нет ни в одной стране, в указанных вами рамках.')
Вы не совсем правильно интерпретировали задание.
1) Получаете число от пользователя (N) - это число стран со списками городов.
2) Теперь N раз запрашиваете у пользователя строку вида "страна город1 город2 город3 город4 ...".
3) Из этой строки формируете словарь вида "город": ["страна", ...].
4) На каждой итерации пополняете этот словарь. Если город уже есть в словаре, то расширяете список стран, в которые он входит.
5) Запрашиваете у пользователя новое число (M).
6) Запрашиваете M строк, в которых пользователь будет вводить один город.
7) Для каждого такого запроса выводите список стран, в которые входит этот город.

2023-08-21 12:06 UTC, a-kosak-mbx approved these changes
Отлично.

2023-08-21 13:02 UTC, merged